### ISSUE TITLE
Problems exporting figures in svg format

### ISSUE THREAD

**Issue by ameyakhandekar2810** [baigouy/ScientiFig#1]
Dear Aigouy,
I recently began to use ScientiFig again after a long hiatus.  I am unable to export figures as .svg files, which I used to be able to. Is there a fix for this? Thanks a lot!

**Comment by baigouy** [comment]
Dear @ameyakhandekar2810,

Thanks for using our tool. It's hard for me to know what may have gone wrong. The only thing I can say is that I cannot reproduce the problem here (linux) with a fresh install of FIJI and a fresh install of EZFig (more modern UI for ScientiFig).  When I import a few sample images from ImageJ into EZFig and export them as svg it generates a functional svg file that I can open and edit with Inkscape. So I assume you may be using a very old version of FIJI/ScientiFig that may not have been updated in a while ?

what I recomment is to do a fresh install of FIJI from:

https://fiji.sc/

then within FIJI do

-Help>Update...>Manage update sites 
-then scroll and tick 'ScientiFig' or 'EZFig'
-then let it install and restart
-then open EZFig or scientifg and try to save as svg againn it should work

hope this helps and let me know otherwise

Benoit
